language: java
jdk: openjdk17
before_install:
  - chmod +x prepare-build.sh
  - ./prepare-build.sh
script: mvn package
after_success:
  - cd /tmp
  - git clone https://${GH_USER_NAME}:${GH_TOKEN}@github.com/${GH_USER_NAME}/${GH_PROJECT_NAME} innerbuilder
  - cd innerbuilder
  - cp $TRAVIS_BUILD_DIR/innerbuilder.jar .
  - git config --global user.name $GIT_AUTHOR_NAME
  - git config --global user.email $GIT_AUTHOR_EMAIL
  - git add innerbuilder.jar
  - git commit -m "[ci skip] Committed by Travis-CI"
  - git push https://${GH_USER_NAME}:${GH_TOKEN}@github.com/${GH_USER_NAME}/${GH_PROJECT_NAME}
env:
  global:
  - GH_USER_NAME: analytically
  - GH_PROJECT_NAME: innerbuilder
  - GIT_AUTHOR_NAME: TravisCI
  - GIT_AUTHOR_EMAIL: noreply@travis-ci.org
  - CI_HOME=`pwd`/$TRAVIS_REPO_SLUG
  - secure: LXAjFSAiRS5x2bokW3Z07Xq2iOuwXPdrgPUpGZjKIltrzkPASvCyZZFAnNqnDAEkdfQAxnPGHPory53PkplakwnpVa8z9Ehw33sH5qMBsBxGJAtH+x7VEfpUdtw83hsU/mBD9D5evSyjN87rUABXX5BuM0l6gHprkGuxdNA7CEc=
